services:
  MSpdf:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SIMPLE_MODE: false # false for default mode, true for simple mode
    container_name: MSpdf
    ports:
      - '8080:8080'
    restart: unless-stopped
    # For IPv4-only environments
    #environment:
    #  - DISABLE_IPV6=true
