{{- if .Values.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ default (include "chart.fullname" .) .Values.gateway.name }}
  namespace: {{ default .Release.Namespace .Values.gateway.namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ required "values.gateway.gatewayClassName is required when gateway.enabled=true" .Values.gateway.gatewayClassName }}
  listeners:
    {{- toYaml .Values.gateway.listeners | nindent 4 }}
{{- end }}
